auth_enabled: false

server:
  http_listen_port: 3100

analytics:
  reporting_enabled: false

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /opt/apps/monitor/storage/loki/data/chunks
      rules_directory: /opt/apps/monitor/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /opt/apps/monitor/storage/loki/data/index
chunk_store_config:
  max_look_back_period: 72h

compactor:
  working_directory: /tmp/loki/retention
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  delete_request_cancel_period: 5m
  retention_delete_delay: 5m
  retention_delete_worker_count: 150

limits_config:
  retention_period: 72h
